/**
 * Types of ErrorCodes
 * @enum {String}
 */
const ERROR_CODES = {
    ABORT_ON_TIMEOUT_ERROR: 'ABORT_ON_TIMEOUT_ERROR',
    API_OFFLINE: 'API_OFFLINE',
    ALREADY_REGISTERED: 'ALREADY_REGISTERED',
    ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
  };
  
  export default ERROR_CODES;
  